services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./local:/app/local
    environment:
      # Add any environment variables needed for development here
      # For example, if you connect to a local database
      DATABASE_URL: "sqlite:///app/local/db.db"
    command: >
      sh -c "atlas migrate hash --dir file://migrations &&
             atlas migrate apply --url sqlite:///app/local/db.db --dir file://migrations &&
             swag init -g cmd/api/main.go -o docs &&
             air"


