name: Deploy to Production

on:
  push:
    branches:
      - main

env:
  TURSO_DB_URL: ${{ secrets.TURSO_DB_URL }}
  TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install Atlas CLI
        run: |
          curl -sSf https://atlasgo.sh | sh

      - name: Install Swagger CLI
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest

      - name: Generate Swagger documentation
        run: |
          swag init -g cmd/api/main.go -o docs

      - name: Hash migration directory
        run: atlas migrate hash --dir "file://migrations"

      - name: Apply database migrations
        run: atlas migrate apply --url "$TURSO_DB_URL?authToken=$TURSO_AUTH_TOKEN" --dir "file://migrations"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.production
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/xeodocs-dash-api:latest
