name: Deploy to Production

on:
  push:
    branches:
      - main

env:
  TURSO_DB_URL: ${{ secrets.TURSO_DB_URL }}
  TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc

      - name: Install migrate CLI
        run: |
          CGO_ENABLED=1 go install -tags 'libsql' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
          # Verify the installation worked
          migrate --version

      - name: Apply database migrations
        run: migrate -path migrations -database "$TURSO_DB_URL?authToken=$TURSO_AUTH_TOKEN" up

      - name: Build Go application
        run: CGO_ENABLED=0 go build -o main .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.production
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/xeodocs-dash-api:latest
          platforms: linux/amd64,linux/arm64
